version: '3.8'
services:
  discord:
    image: node:lts
    container_name: tangled-radio-discordbot
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./src:/home/node/app/src
      - ./node_modules:/home/node/app/node_modules
      - ./package.json:/home/node/app/package.json
      - ./package-lock.json:/home/node/app/package-lock.json
    env_file:
      - .env
    environment:
      NODE_ENV: production
    command: apt-get update -y && apt-get install -y ffmpeg && node ./src/index.js