version: '3.8'
services:
  discord:
    image: node:lts
    container_name: tangled-radio-discordbot
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    env_file:
      - .env
    environment:
      NODE_ENV: production
    entrypoint: /home/node/app/entrypoint.sh