version: '3.8'
services:
  discord:
    image: node:lts
    container_name: tangled-radio-discordbot
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./src:/home/node/app/src
      - ./node_modules:/home/node/app/node_modules
      - ./package.json:/home/node/app/package.json
      - ./package-lock.json:/home/node/app/package-lock.json
      - ./entrypoint.sh:/home/node/app/entrypoint.sh
    env_file:
      - .env
    environment:
      NODE_ENV: production
    entrypoint: /home/node/app/entrypoint.sh